package love.miao.yun.ui.theme

import androidx.compose.ui.graphics.Color

// ==================== Color Palette Data Class ====================
data class NekoColorPalette(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val errorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
)

// ==================== GR (翡翠绿) ====================
val GRGreenLight = NekoColorPalette(
    primary = Color(0xFF4C662B),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFCDEDA3),
    onPrimaryContainer = Color(0xFF354E16),
    secondary = Color(0xFF586249),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFDCE7C8),
    onSecondaryContainer = Color(0xFF404A33),
    tertiary = Color(0xFF386663),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFBCECE7),
    onTertiaryContainer = Color(0xFF1F4E4B),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    background = Color(0xFFF9FAEF),
    onBackground = Color(0xFF1A1C16),
    surface = Color(0xFFF9FAEF),
    onSurface = Color(0xFF1A1C16),
    surfaceVariant = Color(0xFFE1E4D5),
    onSurfaceVariant = Color(0xFF44483D),
    outline = Color(0xFF75796C),
    outlineVariant = Color(0xFFC5C8BA),
)

val GRGreenDark = NekoColorPalette(
    primary = Color(0xFFB1D18A),
    onPrimary = Color(0xFF1F3701),
    primaryContainer = Color(0xFF354E16),
    onPrimaryContainer = Color(0xFFCDEDA3),
    secondary = Color(0xFFC0CBAF),
    onSecondary = Color(0xFF2C3419),
    secondaryContainer = Color(0xFF404A33),
    onSecondaryContainer = Color(0xFFDCE7C8),
    tertiary = Color(0xFFA0D0CB),
    onTertiary = Color(0xFF003734),
    tertiaryContainer = Color(0xFF1F4E4B),
    onTertiaryContainer = Color(0xFFBCECE7),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    background = Color(0xFF12140E),
    onBackground = Color(0xFFE2E3D8),
    surface = Color(0xFF12140E),
    onSurface = Color(0xFFE2E3D8),
    surfaceVariant = Color(0xFF44483D),
    onSurfaceVariant = Color(0xFFC5C8BA),
    outline = Color(0xFF8F9285),
    outlineVariant = Color(0xFF44483D),
)

// ==================== Ember (琥珀暖) ====================
val EmberLight = NekoColorPalette(
    primary = Color(0xFF7C5800),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFFDEA1),
    onPrimaryContainer = Color(0xFF271900),
    secondary = Color(0xFF6E5C3F),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFF8DFBB),
    onSecondaryContainer = Color(0xFF271900),
    tertiary = Color(0xFF4D653D),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFCFF0B4),
    onTertiaryContainer = Color(0xFF0C2000),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    background = Color(0xFFFFF8F3),
    onBackground = Color(0xFF201B13),
    surface = Color(0xFFFFF8F3),
    onSurface = Color(0xFF201B13),
    surfaceVariant = Color(0xFFEDE1CF),
    onSurfaceVariant = Color(0xFF4F4539),
    outline = Color(0xFF827567),
    outlineVariant = Color(0xFFD5C5B5),
)

val EmberDark = NekoColorPalette(
    primary = Color(0xFFFFDEA1),
    onPrimary = Color(0xFF402D00),
    primaryContainer = Color(0xFF5C4100),
    onPrimaryContainer = Color(0xFFFFDEA1),
    secondary = Color(0xFFDBC4A0),
    onSecondary = Color(0xFF3F2E14),
    secondaryContainer = Color(0xFF564429),
    onSecondaryContainer = Color(0xFFF8DFBB),
    tertiary = Color(0xFFB4D499),
    onTertiary = Color(0xFF213612),
    tertiaryContainer = Color(0xFF374D28),
    onTertiaryContainer = Color(0xFFCFF0B4),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    background = Color(0xFF18130D),
    onBackground = Color(0xFFEDE0D0),
    surface = Color(0xFF18130D),
    onSurface = Color(0xFFEDE0D0),
    surfaceVariant = Color(0xFF4F4539),
    onSurfaceVariant = Color(0xFFD5C5B5),
    outline = Color(0xFF9E8E7E),
    outlineVariant = Color(0xFF4F4539),
)

// ==================== Glacier (冰川蓝) ====================
val GlacierLight = NekoColorPalette(
    primary = Color(0xFF005AC1),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFD8E2FF),
    onPrimaryContainer = Color(0xFF001A41),
    secondary = Color(0xFF565E71),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFDAE2F9),
    onSecondaryContainer = Color(0xFF131C2C),
    tertiary = Color(0xFF006B5F),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFF72F8E3),
    onTertiaryContainer = Color(0xFF00201C),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    background = Color(0xFFFDFBFF),
    onBackground = Color(0xFF1B1B1F),
    surface = Color(0xFFFDFBFF),
    onSurface = Color(0xFF1B1B1F),
    surfaceVariant = Color(0xFFE0E2EC),
    onSurfaceVariant = Color(0xFF44474F),
    outline = Color(0xFF74777F),
    outlineVariant = Color(0xFFC4C6D0),
)

val GlacierDark = NekoColorPalette(
    primary = Color(0xFFADC6FF),
    onPrimary = Color(0xFF002E69),
    primaryContainer = Color(0xFF004494),
    onPrimaryContainer = Color(0xFFD8E2FF),
    secondary = Color(0xFFBEC6DC),
    onSecondary = Color(0xFF283041),
    secondaryContainer = Color(0xFF3E4759),
    onSecondaryContainer = Color(0xFFDAE2F9),
    tertiary = Color(0xFF51DBC7),
    onTertiary = Color(0xFF003731),
    tertiaryContainer = Color(0xFF005047),
    onTertiaryContainer = Color(0xFF72F8E3),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    background = Color(0xFF1B1B1F),
    onBackground = Color(0xFFE3E2E6),
    surface = Color(0xFF1B1B1F),
    onSurface = Color(0xFFE3E2E6),
    surfaceVariant = Color(0xFF44474F),
    onSurfaceVariant = Color(0xFFC4C6D0),
    outline = Color(0xFF8E9099),
    outlineVariant = Color(0xFF44474F),
)
